version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: buildefect-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: buildefect-backend
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      JWT_SECRET: replace-this-secret
      IS_DOCKER: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./internal/uploads:/app/internal/uploads

volumes:
  pgdata:
